version: '3'
volumes: 
  static_files:
services:
  django:
    container_name: django_server
    build:
      context: .
      dockerfile: docker_compose/docker/Dockerfile
    # command: /start.sh
    volumes:
      - static_files:/static_files
    ports:
      - 8000:8000
    command: gunicorn -w 4 quiz.wsgi -b 0.0.0.0:8000

  nginx:
    container_name: nginx_server
    build:
      context: .
      dockerfile: docker_compose/nginx/Dockerfile
    # depends_on:
    #   - django
    # volumes:
    #   - ./docker_compose/nginx/django.conf:/etc/nginx/conf.d/django.conf
    ports:
      - 443:80