# Generated by Django 3.0 on 2019-12-13 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.CharField(max_length=100)),
                ('choise1', models.CharField(max_length=50)),
                ('choise2', models.CharField(max_length=50)),
                ('choise3', models.CharField(max_length=50)),
                ('choise4', models.CharField(max_length=50)),
                ('answer', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('url', models.URLField(null=True, verbose_name='URL')),
            ],
        ),
    ]
