version: '3'

services:
  django:
    container_name: django_server
    build:
      context: .
      dockerfile: ./docker_compose/django/Dockerfile
    user: django
    command: /start.sh
    env_file: .env

  nginx:
    container_name: nginx_server
    build: ./docker_compose/nginx
    depends_on:
      - django
    ports:
      - "0.0.0.0:80:80"


